# My first ever python script!
print("Hello there")
print("                 ________________")
print("        /|      |                |                 ")
print("       / |      |  ___      ___  |                 ")
print("      /  |      |  |_|      |_|  |                 ")
print("     /   |      |                |                 ")
print("    /    |      |  |__________|  |                 ")
print("   /     |      |                |                 ")
print("  /      |      |________________|            ")
print(" /       |            Some random shapes and stuff  ")
print("/________|     ___________                                 ")
print("               |         |            /\                           ")
print("               |         |           /  \                          ")
print("               |         |          /    \                         ")
print("               |         |         /      \                        ")
print("               |         |        /        \                       ")
print("               |         |       /          \                      ")
print("               |         |      /            \                     ")
print("               |         |     /              \                    ")
print("               |_________|    /________________\                   ")
print("   _______      ")
print("  |  _____|      ")
print("  |  |")
print("  |  |___ ")
print("  |  ____|")
print("  |  | ")
print("  |  | ")
print("  |__| ")
print("                      eeeeeeeeeee     ")
print("general kenobi")




